trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: AzurePowerShell@5
  inputs:
    azureSubscription: '<Your Azure ARM Service Connection Name>'
    ScriptType: 'InlineScript'
    Inline: |
      New-AzSubscriptionDeployment -Name sitetest -Location eastus -TemplateFile .\main.bicep `
      -TemplateParameterFile .\main.param.json
    azurePowerShellVersion: 'LatestVersion'
